// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt7Il8lRfwgCMX2lE-PUHqmqBnMUdGdeE',
    appId: '1:897229586820:web:8f35e420c8c2e6266f9dd1',
    messagingSenderId: '897229586820',
    projectId: 'threads-2ea33',
    authDomain: 'threads-2ea33.firebaseapp.com',
    storageBucket: 'threads-2ea33.appspot.com',
    measurementId: 'G-1K5SQF2LFT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM9g03Isxklza4aAPzALe8qVea4XhjBTQ',
    appId: '1:897229586820:android:38a66bbb8c6682696f9dd1',
    messagingSenderId: '897229586820',
    projectId: 'threads-2ea33',
    storageBucket: 'threads-2ea33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqmCcCa_zgNLCo4UMIZ1J6PG9td12ChkM',
    appId: '1:897229586820:ios:4bf5b542f12572226f9dd1',
    messagingSenderId: '897229586820',
    projectId: 'threads-2ea33',
    storageBucket: 'threads-2ea33.appspot.com',
    iosBundleId: 'com.example.threads',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqmCcCa_zgNLCo4UMIZ1J6PG9td12ChkM',
    appId: '1:897229586820:ios:770b5773d7f6a6346f9dd1',
    messagingSenderId: '897229586820',
    projectId: 'threads-2ea33',
    storageBucket: 'threads-2ea33.appspot.com',
    iosBundleId: 'com.example.threads.RunnerTests',
  );
}
